### ISSUE TITLE
Deploy to Maven Central?

### ISSUE THREAD

**Issue by jschneider** [sekwiatkowski/komputation#5]
Hi mate,

this project looks really, really cool. And I'd like to take a look at it. Could you maybe upload it to Maven Central and make it easy for me and everybody else to give it a shoot?

**Comment by sekwiatkowski** [comment]
Deploying to Maven Central is high up on my to-do list. I hope I can get to this early next week.

**Comment by sekwiatkowski** [comment]
Komputation is now available through MavenCentral:

```xml
<dependency>
    <groupId>com.komputation</groupId>
    <artifactId>komputation</artifactId>
    <version>0.10.1</version>
</dependency>
```
