### ISSUE TITLE
Get current neuron weights from a neural network?

### ISSUE THREAD

**Issue by ejberry** [sekwiatkowski/komputation#7]
Would it be possible to add a method to get the current weights for a neuron in the Network or Layer class? Such information is required for the implementation of [NNPID algorithms](http://research.ijcaonline.org/iciiioes/number9/iciiioes1651.pdf) and other similar control systems.

**Comment by sekwiatkowski** [comment]
Would it help you if I made an array of parameters accessible such that, for example, a weighting layer would return an array consisting of the array/matrix of its weights and a projection layer (weight + bias) would return an array with two items, the weight array and the bias array? Something like: this 

```kotlin
val layer = network.getLayer(1) as HasParameters
val weight = layer.getParameters()[parameterIndex][weightIndex]
```

Can you tell me a bit more about the application that you are working on? I'm curious!

**Comment by ejberry** [comment]
Accessing the parameters as such should be fine. 

The program we're working on is a software library to simplify handling of different data acquisition and control systems. End goal being a single code base which can be used make anything from home automation to a water distillation. Its not open source at the moment, but should be in a couple of months once the preliminary structure is thoroughly tested.

**Comment by sekwiatkowski** [comment]
OK, I will add parameter access.

Please notify me know when your library is released.

**Comment by ejberry** [comment]
Thanks, we'll keep you posted

**Comment by sekwiatkowski** [comment]
Sorry for the delay. I had a medical emergency, vision correction surgery and a lot of other things to do. 

The layers and parameters are accessible starting in v0.10.3. If the first layer is a weighting layer, then the weight can be accessed as follows:

```kotlin
val firstLayer = (network.getLayer(0) as CpuWeightingLayer)
val weights = firstLayer.getWeights()
````
